// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe8UxxhhCusRD3O8W568d33WyrsUOeENw',
    appId: '1:923447053515:web:067e1fadd50343e47e5f4e',
    messagingSenderId: '923447053515',
    projectId: 'fir-practice-3904a',
    authDomain: 'fir-practice-3904a.firebaseapp.com',
    storageBucket: 'fir-practice-3904a.appspot.com',
    measurementId: 'G-ZKYH9V8WHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEVOyrRhcIPTqFBiXISBBqATdYFRXuHcU',
    appId: '1:923447053515:android:67967a3933fdaff17e5f4e',
    messagingSenderId: '923447053515',
    projectId: 'fir-practice-3904a',
    storageBucket: 'fir-practice-3904a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQ8la6KPh9JzHtU2GAvG0AJnuOuJcm4o',
    appId: '1:923447053515:ios:298ab00de8f4d22c7e5f4e',
    messagingSenderId: '923447053515',
    projectId: 'fir-practice-3904a',
    storageBucket: 'fir-practice-3904a.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALQ8la6KPh9JzHtU2GAvG0AJnuOuJcm4o',
    appId: '1:923447053515:ios:298ab00de8f4d22c7e5f4e',
    messagingSenderId: '923447053515',
    projectId: 'fir-practice-3904a',
    storageBucket: 'fir-practice-3904a.appspot.com',
    iosBundleId: 'com.example.firebasePractice',
  );
}
